### ISSUE TITLE
Consider defaulting to skip_all_day to true

### ISSUE THREAD

**Issue by castrojo** [chmouel/gnome-next-meeting-applet#111]
* Gnome Next Meeting applet version: whatever's in flathub
* Python version: Python 3.11.4
* Operating System: Fedora 38

Thanks for making this extension, it's the only sane way to manage my busy schedule! 

### Description

I've been testing this extension with some friends and we all ran into the same problem, if the next day is a full day it shows up as the text and then I have to click each time I want to see my actual next meeting. Then we discovered `skip_all_day: true` and now I can see my next actual meeting. 

Alternatively, having it in the gui so it's easy to see and turn off would be great.

**Comment by chmouel** [comment]
I think that seems reasonable...

I really wanted to do a GUI for settings but unfortunately have been lacking motivations (and i'm not much of a GUI person), i'll try to make a pinned issue to see if someone with my GUI knowledge than me wants to contribute
