### ISSUE TITLE
flatpak installing gnome 41

### ISSUE THREAD

**Issue by danieltomasz** [chmouel/gnome-next-meeting-applet#115]
* Gnome Next Meeting applet version: 2.10.1
* Python version:
* Operating System: Ubuntu 23.04 

I am installing applet via
```
flatpak install flathub com.chmouel.gnomeNextMeetingApplet
```

Outdated Gnome 41 is pulled as dependency (according to some of the releases notes the dependencies were updated to gnome 43)

**Comment by chmouel** [comment]
i believe this should be fixed by https://github.com/flathub/com.chmouel.gnomeNextMeetingApplet/pull/8 thanks to @bbhtt
