### ISSUE TITLE
Latest version v2.12.2 not available in FlatHub 

### ISSUE THREAD

**Issue by nlevee** [chmouel/gnome-next-meeting-applet#134]
### Description

In [flathub](https://flathub.org/en/apps/com.chmouel.gnomeNextMeetingApplet) the new version v2.12.2 is not available

**Comment by chmouel** [comment]
Heu that's weird, it's built green and merged there:

https://github.com/flathub/com.chmouel.gnomeNextMeetingApplet

and usually that makes it appears on flathub.org 🤔

**Comment by chmouel** [comment]
I wonder who can I contact for help,
