### ISSUE TITLE
Doesn't fetch newly added events

### ISSUE THREAD

**Issue by logix2** [chmouel/gnome-next-meeting-applet#14]
* Gnome Next Meeting applet version: 1.3.0
* Python version: 3.9.7
* Operating System: Ubuntu 21.10

Newly added events are not loaded by Gnome Next Meeting applet while it's running. I have ``refresh_interval: 300`` in the configuration file, but it doesn't seem to actually refresh anything. The only way to get new events to show up is to restart  Gnome Next Meeting applet. I tested a few times, always with the same result.

**Comment by chmouel** [comment]
humm strange this seems to work for me, I would think it's working for me but will need to double check, can you see them in evolution or gnome calendar?

**Comment by logix2** [comment]
Yes, the event shows up in Gnome Calendar, but doesn't in Gnome Next Meeting applet. I don't have Evolution installed.

**Comment by chmouel** [comment]
sounds good thanks, will investigate!
