### ISSUE TITLE
Doesn't show most calendars

### ISSUE THREAD

**Issue by rorymobley** [chmouel/gnome-next-meeting-applet#19]
* Gnome Next Meeting applet version: 1.6.1
* Python version: 3.10
* Operating System: Fedora 35

### Description

Only the main and holidays calendars show up. Not even the TV calendar shows up, which is just a normal google calendar like main and holidays (not remote ical, I mean).
### What I Did

```
Wondering what was wrong, I looked at the documentation and config.yaml. No matter what I tried, including just the defaults, those other calendars in my Google account do not show (they do show in Evolution).
Currently here's my config:
calendar_day_prefix_url: https://calendar.google.com/calendar/r/day/
max_results: 30
skip_non_accepted: false
title_max_char: 11

```

**Comment by chmouel** [comment]
humm weird, i know that gnome online account sometime doesn't want to give us everythings sometime  while gnome-calendar or evolution shows it.  same goes for some events missing when we request via the ecal api. 

will try to figure out why is that,

**Comment by chmouel** [comment]
I have added some debugging flag in master "-v" to help debug which events has been skipped and received from goa

**Comment by rorymobley** [comment]
I'm assuming that the interesting bits are repeated e-data-server-CRITICAL errors: 
[rory@fedora ~]$ gnome-next-meeting-applet -v
DEBUG:root:refreshing goa calendars event

(gnome-next-meeting-applet:6288): e-data-server-CRITICAL **: 07:16:34.399: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:6288): e-data-server-CRITICAL **: 07:16:34.410: client_set_source: assertion 'E_IS_SOURCE (source)' failed

There were a couple more of those same errors. The only other outputs are skipping because they're over a month away

**Comment by chmouel** [comment]
ah that's what i tought, GOA doesn't give us all the informations we want sometime :\ 

will need to think about another method of accessing the calendar the same way gnome-calendar/evo does with goa driver

**Comment by chmouel** [comment]
This needed more works than i tought, i have almost remade most of the code of this applet, if you have some time to try this branch : 

https://github.com/chmouel/gnome-next-meeting-applet/tree/2.0

running it should be simple as : 

```
% python3 gnma/cli.py
```
