### ISSUE TITLE
2.0.1 error on fedora 35

### ISSUE THREAD

**Issue by roryst** [chmouel/gnome-next-meeting-applet#22]
* Gnome Next Meeting applet version: 2.0.1
* Python version: 3.10
* Operating System: fedora 35

### Description

just launching it

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
[rory@fedora ~]$ gnome-next-meeting-applet 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 152, in set_indicator_icon_label
    self.indicator.set_label(f"{self.first_event_label(event)}",
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 102, in first_event_label
    humanized_str = strings.humanize_time(event.start_dttime,
  File "/usr/lib/python3.10/site-packages/gnma/strings.py", line 49, in humanize_time
    return humanize.naturaldelta(
TypeError: naturaldelta() got an unexpected keyword argument 'when'


```

I don't see anything on my bar any more (I used to see at least some calendars in the previous versions). this one shows a little calendar icon in the app indicator section, but it does nothing. cant right click, cant set up anything or see anything.

**Comment by chmouel** [comment]
oh thanks for this, i guess multi distro support is hard ! will try to get this fixed asap

**Comment by chmouel** [comment]
woo fedora version is 0.5 when upstream is 3.5

**Comment by chmouel** [comment]
not completly fixed yet 😞 

```
DEBUG:root:[skipping] elapsed: Tekton / OpenShift Pipelines Planning
Traceback (most recent call last):
  File "/home/chmouel/GIT/go/src/github.com/chmouel/gnome-next-meeting-applet/gnma/applet.py", line 152, in set_indicator_icon_label
    self.indicator.set_label(f"{self.first_event_label(event)}",
  File "/home/chmouel/GIT/go/src/github.com/chmouel/gnome-next-meeting-applet/gnma/applet.py", line 102, in first_event_label
    humanized_str = strings.humanize_time(event.start_dttime,
  File "/home/chmouel/GIT/go/src/github.com/chmouel/gnome-next-meeting-applet/gnma/strings.py", line 55, in humanize_time
    return humanize.precisedelta(start_time + datetime.timedelta(minutes=1),
AttributeError: module 'humanize' has no attribute 'precisedelta'
```

**Comment by chmouel** [comment]
released 2.0.4 with fix, let me know how it goes if  you have some time to try this on,

**Comment by rorymobley** [comment]
with 2.0.4, i receive no errors. my only concern is... before the rewrite, we could click on the applet and there would be a list of events and settings. Now that menu is gone and clicking in any way does nothing. Is that intentional in the rewrite? Thanks!!

**Comment by chmouel** [comment]
humm no it should be the same thing, are you getting the events on
gnome-calendar, is your GOA account connected?

**Comment by rorymobley** [comment]
GOA. it's mostly working because it is showing my next events on the
bar itself (and it seems to be going through every single calendar
correctly), but once i click on the applet to see more upcoming,
nothing happens. no menu comes up.

**Comment by chmouel** [comment]
oh okay, weird one, which system do you use ? which version of
the appindicator extension ?

**Comment by rorymobley** [comment]
it's fedora 35 with gnome 41.1

**Comment by danastasio** [comment]
@chmouel I am having this same problem, but am using the flatpak version from Flathub. Also on Fedora 35 but with Gnome 41.3.

```flatpak run com.chmouel.gnomeNextMeetingApplet``` gives the following error:

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gnma/gnome_online_account_cal.py", line 130, in view_objects_added
    self.handle_new_or_modified_objects(view,
  File "/app/lib/python3.9/site-packages/gnma/gnome_online_account_cal.py", line 260, in handle_new_or_modified_objects
    ical_time_modified = mod_prop.get_lastmodified()
AttributeError: 'NoneType' object has no attribute 'get_lastmodified'
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gnma/gnome_online_account_cal.py", line 187, in recurrence_generated
    ical_time_modified = mod_prop.get_lastmodified()
AttributeError: 'NoneType' object has no attribute 'get_lastmodified'
```

Do you need any more information? Would you like me to open a new issue for this?

**Comment by chmouel** [comment]
Thanks for the report this seems a different issue ,any chance you can start a new issue and I'll see how I can hepl you debug from there ? Cheers
