### ISSUE TITLE
[Feature request] Integration in "notifications and messaging tray"

### ISSUE THREAD

**Issue by 7system7** [chmouel/gnome-next-meeting-applet#29]
Firstly, I would like to thank you for your work. It is a great app, it should be a part by-default the GNOME.

## Description

Actually, I have 3 idea

1. It would be good, if there is an option that can integrate this app to the messaging tray, below the mini-calendar, for example.
    ![Screenshot from 2022-02-03 09-58-04](https://user-images.githubusercontent.com/3964568/152312087-9548dedf-3eb5-4bea-a3f6-492b71090761.png)
1. The text is too long, (on the panel) and it is not changeable. For example, I think, it is enough to view the remaining time in this format: "3:10 | <title>" Or it would be nice, I can see only one icon. Maybe the best option is to define the format of the message on the panel, like [this](https://extensions.gnome.org/extension/1206/clock-override/): 
    ![screenshot_1206_PnOtEcE](https://user-images.githubusercontent.com/3964568/152312747-64bd5532-3fbe-4a0b-8b8e-ff32d05b9418.png)
1. The default application should be changeable. For example w/ Zoom link, it does not matter, which browser will open it, cause' it has a dedicated desktop app. Google Meet is not. I use Firefox for almost everything, but, i.e.: the Meet does not support the background visual effects. So, I use it in Chromium. (And I’m probably not alone with my decision.)
   ![Screenshot from 2022-02-03 10-14-28](https://user-images.githubusercontent.com/3964568/152313731-61291ec9-0839-4b75-a8ed-50cb535a5e48.png)

**Comment by chmouel** [comment]
Hey, i'd love to support the panel notification but this would mean rewriting this as a vala/javascript extension which goes beyond my skills..

The multipe browser support make a lot of sense, we just need a UI for configuration to be able to do it properly.

I currently use a wrapper script that switch browser on url (ie: https://meet.google.com/* to open on chrome and other in firefox)
