### ISSUE TITLE
gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by jevy** [chmouel/gnome-next-meeting-applet#31]
* Gnome Next Meeting applet version: `2.6.2`
* Python version: Assuming it's installed with flatpak
* Operating System: NixOS

### Description

I installed the Flatpak version on my NixOS machine and trying to run it :D

### What I Did

```
flatpak install flathub com.chmouel.gnomeNextMeetingApplet
flatpak run com.chmouel.gnomeNextMeetingApplet
```
It returns:
`(gnome-next-meeting-applet:2): Gtk-CRITICAL **: 06:02:06.554: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

Nothing appears to start in the UI.

**Comment by chmouel** [comment]
Hello, sorry I just saw this, this is very weird,  flatpak should "just works", does any other gtk based flatpak application works for you?

**Comment by hofq** [comment]
Hey there, i have the Same issue with the AUR build
Kernel: 5.19.1-zen1-1-zen
GNOME: 42.4
<details>
<summary>Installed GNOME Packages</summary>
gnome-autoar 0.4.3-2
gnome-backgrounds 42.0-1
gnome-bluetooth-3.0 42.2-1
gnome-books 40.0-1
gnome-boxes 42.3-1
gnome-browser-connector 42.0-2
gnome-builder 42.1-2
gnome-calculator 42.2-1
gnome-calendar 42.2-1
gnome-characters 42.0-1
gnome-chess 42.1-1
gnome-clocks 42.0-1
gnome-color-manager 3.36.0+r25+g4aab8b59-1
gnome-connections 42.1.2-1
gnome-contacts 42.0-1
gnome-control-center 42.3-1
gnome-desktop 1:42.4-1
gnome-desktop-4 1:42.4-1
gnome-desktop-common 1:42.4-1
gnome-devel-docs 40.3-1
gnome-disk-utility 42.0-1
gnome-epub-thumbnailer 1.6-2
gnome-font-viewer 42.0-1
gnome-games 40.0-3
gnome-keyring 1:42.1-1
gnome-klotski 3.38.2-1
gnome-logs 42.0-1
gnome-mahjongg 3.38.3-1
gnome-maps 42.3-1
gnome-menus 3.36.0-2
gnome-mines 40.1-1
gnome-multi-writer 3.32.1-2
gnome-music 1:42.1-1
gnome-nettool 42.0-1
gnome-network-displays 0.90.5-4
gnome-next-meeting-applet 2.8.1-1
gnome-nibbles 3.38.2-1
gnome-online-accounts 3.44.0-1
gnome-photos 1:42.0-1
gnome-recipes 2.0.4-3
gnome-remote-desktop 42.4-1
gnome-robots 40.0-1
gnome-session 42.0-1
gnome-settings-daemon 42.2-1
gnome-shell 1:42.4-1
gnome-shell-extension-appindicator 42-1
gnome-shell-extensions 42.3-1
gnome-software 42.4-1
gnome-sound-recorder 42.0-1
gnome-sudoku 42.0-1
gnome-system-monitor 42.0-1
gnome-taquin 3.38.1-1
gnome-terminal 3.44.1-1
gnome-tetravex 3.38.2-1
gnome-todo 41.0+r106+gebc68374-1
gnome-tweaks 42beta+r14+g2d9d76c-2
gnome-usage 3.38.1-1
gnome-user-docs 42.0-1
gnome-user-share 3.34.0-2
gnome-video-effects 0.5.0+4+g9554041-2
gnome-weather 42.0-1
libgnome-games-support 1.8.2-2
libgnome-keyring 3.12.0+13+g4f8ab73-3
libgnomekbd 1:3.26.1+r5+g54da436-1
polkit-gnome 0.105-9
xdg-desktop-portal-gnome 42.3-1
</details>
