### ISSUE TITLE
applet is missing

### ISSUE THREAD

**Issue by hofq** [chmouel/gnome-next-meeting-applet#41]
* Gnome Next Meeting applet version:  2.8.1-1
* Python version: 3.10.6
* Operating System: Arch Linux x86_64
* GNOME Version: 42.4

### Description

I tried installing the gnome-next-meeting-applet using AUR (+ Flatpak) and had no success. I don't get any error (even in verbose) but the Applet just does not show up.

### What I Did

```bash
paru -S gnome-next-meeting-applet
sudo pacman -S gnome-shell-extension-appindicator
# logout + login
gnome-next-meeting-applet & gnome-next-meeting-applet -v
```
I also removed the gnome-next-meeting-applet and installed it with flatpak

The Top Bar shows nothing that indicates the applet is running:
![image](https://user-images.githubusercontent.com/54744977/186140564-288af8c5-ee69-44ba-9f36-243106974df0.png)

If i run with sudo i at least get an error in the Terminal and an Icon in the Top Bar
![image](https://user-images.githubusercontent.com/54744977/186140417-9fa914f5-d8d0-4d24-ba37-44d96d3a5c9c.png)
<details>
<summary>Error with sudo</summary>

[jki@TPJKI01-arch ~]$ sudo gnome-next-meeting-applet
[sudo] password for jki: 

(gnome-next-meeting-applet:52029): libappindicator-WARNING **: 12:52:13.842: Unable to get the session bus: Error spawning command line “dbus-launch --autolaunch=085b01f836f44de797b27fcb26597012 --binary-syntax --close-stderr”: Child process exited with code 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gnma/gnome_online_account_cal.py", line 46, in goa_registry_callback
    self.registry = EDataServer.SourceRegistry.new_finish(res)
gi.repository.GLib.GError: g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=085b01f836f44de797b27fcb26597012 --binary-syntax --close-stderr”: Child process exited with code 1 (1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gnma/gnome_online_account_cal.py", line 48, in goa_registry_callback
    raise GnomeOnlineAccountError from gliberror
gnma.gnome_online_account_cal.GnomeOnlineAccountError

(gnome-next-meeting-applet:52029): Gdk-CRITICAL **: 12:52:14.026: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
^CTraceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet", line 33, in <module>
    sys.exit(load_entry_point('gnome-next-meeting-applet==2.8.1', 'console_scripts', 'gnome-next-meeting-applet')())
  File "/usr/lib/python3.10/site-packages/gnma/cli.py", line 36, in cli
    applet.run(args)
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 334, in run
    Applet(args).run()
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 330, in run
    gtk.main()
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 1687, in main
    with register_sigint_fallback(Gtk.main_quit):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

</details>

### Verbose output

```log
[jki@TPJKI01-arch ~]$ gnome-next-meeting-applet -v
DEBUG:root:loading configfile: /home/jki/.config/gnome-next-meeting-applet/config.yaml
DEBUG:root:Watching calendar Birthdays & Anniversaries
DEBUG:root:Watching calendar Calendar
DEBUG:root:Watching calendar Geburtstage von Kontakten
DEBUG:root:Watching calendar Personal
DEBUG:root:Watching calendar Persönlich
DEBUG:root:Watching calendar Worklog

```

**Comment by yawks** [comment]
Hello,

Do you have the gnome-extension "AppIndicator and KStatusNotifierItem Support" Enabled?
![image](https://user-images.githubusercontent.com/4396128/190637428-77ab1909-acdb-4265-aee0-6c81bf978272.png)

**Comment by hofq** [comment]
> Hello,
> 
> Do you have the gnome-extension "AppIndicator and KStatusNotifierItem Support" Enabled? ![image](https://user-images.githubusercontent.com/4396128/190637428-77ab1909-acdb-4265-aee0-6c81bf978272.png)

yes

**Comment by hofq** [comment]
now i get this error:
![image](https://user-images.githubusercontent.com/54744977/190976119-c67991bf-fe78-436f-93a9-ce9b86b864fc.png)
and this icon 
![image](https://user-images.githubusercontent.com/54744977/190976148-021b531c-7718-4cc6-aeb5-80a35a6af94b.png)

The Status and App Indicator is enabled:
![image](https://user-images.githubusercontent.com/54744977/190976255-00f9ca5f-bef2-438a-9078-24215ea2c275.png)

**Comment by chmouel** [comment]
it seems this is working, but there seems something on the appindicator side that doesn't let the applet showing up 😞

**Comment by chmouel** [comment]
i think you need to look in your "journalctl --user" logs, I do use the arch/aur as well and i don't have this issue

**Comment by fcsonline** [comment]
I my journal logs I see this after start the the flatpak module:

```
Started app-flatpak-com.chmouel.gnomeNextMeetingApplet-1845473.scope
```

But I also see few lines before:

```
gnome-shell[2748]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
refreshPropertyOnProxy@/home/fcsonline/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:41:38
```

Maybe this issue is related: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/304

**Comment by Samdney** [comment]
Did the same like the first poster (also Arch). Then reloaded shell with Alt + F2 and r. Got an undefined icon. When clicking on the icon I get the following python error:
```
$ gnome-next-meeting-applet &

$ Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 164, in set_indicator_icon_label
    event = self.get_event()
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 159, in get_event
    return self.all_events[self.last_sorted[0]]
IndexError: list index out of range

(gnome-next-meeting-applet:805378): Gdk-CRITICAL **: 23:33:19.303: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

```

**Comment by Samdney** [comment]
> Did the same like the first poster (also Arch). Then reloaded shell with Alt + F2 and r. Got an undefined icon. When clicking on the icon I get the following python error:
> 
> ```
> $ gnome-next-meeting-applet &
> 
> $ Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 164, in set_indicator_icon_label
>     event = self.get_event()
>   File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 159, in get_event
>     return self.all_events[self.last_sorted[0]]
> IndexError: list index out of range
> 
> (gnome-next-meeting-applet:805378): Gdk-CRITICAL **: 23:33:19.303: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
> ```

When scanning through the source code, can it be that the applet expect at least one event? If yes, then that could cause the error, since my online accounts are right now offline, so that it can't retrieve any calender events from somewhere and is unable to handle this case?

**Comment by chmouel** [comment]
This is weird as I cannot reproduce this with the same setup and perhaps it's because of the calendar as @Samdney mentions, this probably would fix this the error but will need to be tested : 

```diff
% diff -u  /usr/lib/python3.10/site-packages/gnma/applet.py /tmp/applet.py
--- /usr/lib/python3.10/site-packages/gnma/applet.py	2022-07-13 09:11:18.000000000 +0200
+++ /tmp/applet.py	2022-09-25 21:56:44.213459458 +0200
@@ -154,7 +154,8 @@
         gtk.show_uri(None, source.location, gtk.get_current_event_time())
 
     def get_event(self):
-        if len(self.all_events) > 0:
+        if len(self.all_events) > 0 and self.last_sorted and \
+                self.last_sorted[0] in self.all_events:
             self.make_menu_items()
             return self.all_events[self.last_sorted[0]]
         return None
```

I may  just release a new version with it since it anyway make sense to check for thosvalues...

**Comment by hofq** [comment]
For me the Issue was related to the Gnome User Account Management.

We use O365 at work and Gnome does not support that as it seems. I have configured the O365 Exchange but i get errors in journalctl. From what i have read in some Forums there is no support and on some of these issues there was no reply for the last 3 Years. 

I think i'm just out of luck then. Thanks for your help @all

**Comment by chmouel** [comment]
ah that make sense, the python error, since it would not find anything..

sorry to hear about that, been a long time since i have been using exchange but wasn't there some software that can bridge  exchange to caldav/imap on your computer locally ?

**Comment by chmouel** [comment]
I mean this software http://davmail.sourceforge.net/
