### ISSUE TITLE
[Feature Request] Support more calendars

### ISSUE THREAD

**Issue by GabLeRoux** [chmouel/gnome-next-meeting-applet#5]
`chmouel/gnome-next-meeting-applet` seems to only support google calenda. It would be really nice to support calendars from [Evolution Calendar](https://help.gnome.org/users/evolution/stable/) which feeds itself from _Settings > Online Accounts_. 

I've been on macOS for quite a while and got used to [the amazing meeter app](https://trymeeter.com/) which shows you upcomming meeting and provides you with direct access to your next meeting's link.

I think `gnome-next-meeting-applet` would definitely be a good alternative for linux users if it had the following features:

* support for multiple calendars (not just google calendar)
* open your next meeting's link in a single click
* notify you 2 minutes before the meeting

Concerning multi calendar support, I went ahead and tried it myself. I managed to retrieve all events from all calendars :rocket:. [Here's what I came up  with so far with `Evolution Calendar Server`](https://askubuntu.com/questions/193954/coding-own-applicaion-for-gnome-shell-calendar/1371087#1371087).

I'll update here if I manage to do further in my next free time.

**Comment by chmouel** [comment]
I just made an update using your code in #6 and it seems to work for me, i'll be using that for a bit testing it and merge it as the default.

Thanks again,
