### ISSUE TITLE
Update the Gnome runtime

### ISSUE THREAD

**Issue by forteller** [chmouel/gnome-next-meeting-applet#74]
Whenever I run flatpak update I get this message:

Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.chmouel.gnomeNextMeetingApplet,

Hope you can update. Thanks! :)

**Comment by chmouel** [comment]
you are right! thanks for letting me know
