### ISSUE TITLE
Meetings don't show up when invited as part of a Google group

### ISSUE THREAD

**Issue by SamyDjemai** [chmouel/gnome-next-meeting-applet#87]
* Gnome Next Meeting applet version: 2.10.1
* Python version: 3.10.6
* Operating System: Ubuntu 22.04.1

### Description

The applet does not show meetings that I've been invited to through a Google group, even if I accept or reject the invitation.

### What I Did

- Be a part of a Google group, eg. my-group@company.com
- Have someone invite my-group@company.com to an event
- The event shows up on Google Calendar and can be accepted or rejected
- The event is missing from the applet

**Comment by SamyDjemai** [comment]
It seemed to be a Gnome Online Accounts problem, switching the **Calendar** toggle off and back on again in the Google account's settings seems to have worked. Sorry for the noise, and thanks for the applet!

**Comment by chmouel** [comment]
no worries, glad you figured it out!
