### ISSUE TITLE
Ignore single-partipant events

### ISSUE THREAD

**Issue by wjdp** [chmouel/gnome-next-meeting-applet#88]
Single participant meetings (e.g. focus time on Google Calendar) are treated as normal events. Is there or can there be a method to filter these out so it only shows events with other people?

**Comment by chmouel** [comment]
Humm I didn't know about those, can you send me a link or an example on how to create those?

**Comment by wjdp** [comment]
In google calendar you can do events like these: 

![image](https://user-images.githubusercontent.com/1690934/225360525-94fe0564-b25e-4d9a-8885-4b581d1be1f0.png)

I'm unsure if that detail surfaces in the data available through the gnome calendar integration. The most basic solution would likely be a config option to ignore events with only a single participant.

My issue is I often have a focus-time event overlapping with meetings and as the focus-time started first I only see that in the bar (I'm on sway)

![image](https://user-images.githubusercontent.com/1690934/225361076-bcf61c93-377a-41ed-b9ff-c1e8cb43a0bd.png)

(Ignore the fact a no-meets weds shouldn't have meeting in it, sadly this doesn't quite map to reality)
(Also the non-standard format is done with an intermediary script)

**Comment by chmouel** [comment]
Sounds good thanks a lot, your solution to have an option to ignore single participant make sense, will try to get this sometime soon..

**Comment by wjdp** [comment]
If I get a chance I may have a look and put in a PR but wanted to check if this is something you fancied added as would take me a while to get to grips with the codebase/ gnome/ical APIs.

**Comment by chmouel** [comment]
would be great! I'll be more than happy to review your PR  if you fancy implementing this feature.
