### ISSUE TITLE
Pull in CalDav Calendars that were entered in Evolution

### ISSUE THREAD

**Issue by whosthegoss** [chmouel/gnome-next-meeting-applet#97]
* Gnome Next Meeting applet version: Latest
* Python version: 3.11.2
* Operating System: Fedora 37

### Description

Using Gnome Next Meeting applet, would like to be able to pull in Calendars that Gnome Calendars also pulls by caldav. These caledars were entered via Evolution Mail via the CalDav addition settings. Calendars are iCloud, but I think it has more to deal the fact that this only pulls from Online Accounts. 
```

**Comment by chmouel** [comment]
It would be nice to have this feature but as you identified it gnma only pull from gnome online account and is not aware of other calendar method outside of this,

I am open to have another extra drivers but this may need to be contributed by someone who can spend some cycle on this.

**Comment by chmouel** [comment]
it is a good idea I think just not something straighforward to do 😭
