### ISSUE TITLE
Please consider alternative naming

### ISSUE THREAD

**Issue by ramcq** [chmouel/gnome-next-meeting-applet#99]
Hi Chmouel,

Thanks for writing this application and adding to the ecosystem of apps available on Flathub for GNOME! 

I'm writing on behalf the GNOME Foundation to ask if you would consider renaming your application so as not to contain the word GNOME.

The GNOME Foundation appointed the GNOME Release Committee in charge of setting the guidelines to define which applications were allowed to use the GNOME trademark. To avoid confusion as to which software is or isn't produced or endorsed by the GNOME project, only applications approved by the release committee (typically only core applications or developer tools) may use the name "GNOME xxx" for their application, according to the software policy: https://wiki.gnome.org/Foundation/SoftwarePolicy

Would it be possible to rename your applet so as to follow this policy? The GNOME HIG contains some recommendations about application naming which you may find helpful: https://developer.gnome.org/hig/guidelines/app-naming.html

Please let me know if you have any queries regarding this and apologies that this wasn't picked up earlier during the Flathub review process.

Many Thanks,
Rob
President on behalf of the GNOME Foundation

**Comment by chmouel** [comment]
Hello, I don't mind renaming it but there is a lot of plumbing and things that needs to get renamed around (ie packages) to get there, i will try to find some time figuring it out what needs to be done..
